# -*- coding: utf-8 -*-
"""Python Code 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pr23dJEbcSCwNAFnUYfnVf3oMwHbmigX
"""

count=0 # init

print("hi") #- this is commented

for count in range(5): # 5 times
  print("move east")
  print("move south")

# variables,

x = 5 # assignment

# int, string, float, double, tuple, list

a=int(input("enter the value of a:"))

type(a)

12->21 # reversal
35->53

a=input("enter a:")

a=str(01)

# array: collection of objects

vector1 = [2,4,5,6,7,-1]

# relation: first 5 odd numbers

vector2 = [1,3,5,7,9]

print(vector1)

vec3 = [3,5,9,11,12,15,18,21]

vec3+1

