# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-sKMscqTsmp5qD8KMdNIMD-EbTxTz6bu
"""

# write a loop to print the days of the month May

for days in range(1,32):
  print("Date is: May",days)

# write the code for summing up the n natural no.s

num=8
sum=0
for n in range(1,num+1): # 1,2,3,4,5,6,7,8
  sum=sum+n
  print("Sum of n =",n,"is:",sum) # commas