# -*- coding: utf-8 -*-
"""Python Code Day 1 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ubx2h-CJ3PiyciEBxo0CgTrKjc_qaIjA
"""

for count in range(4):#

print("move east")
print("move south")
print("move south")
print("move south")

print("move east")
for count in range (3):
  print("move south")

x=y+1

y=6

x=y+1

7=x

print(x)

x

for count